### ISSUE TITLE
How to setup mleap in amazon emr spark cluster?

### ISSUE THREAD

**Issue by guzzijones** [combust/mleap-docs#23]
Hey all I am trying to get mleap to work with Amazon EMR version 5.28.0. I am getting the following error:
`File "/usr/local/lib/python3.6/site-packages/mleap/pyspark/spark_support.py", line 39, in __init__ self._java_obj = _jvm().ml.combust.mleap.spark.SimpleSparkSerializer() TypeError: 'JavaPackage' object is not callable`
I understand the JAR files are most likely not being found.
the spark version is 2.4.4

I have a bootstrap step in a bash file:
`sudo /usr/bin/python3 pip install mleap`

**Comment by cappaberra** [comment]
@guzzijones, there are two components of code you need in order to use MLeap with pyspark:
1. The Spark package (includes the jars)
2. The Python module (the python code that wraps the above jars)

You already got number 2 with your bootstrap step to pip install mleap, but you also need to add Configuration to your run_job_flow() call in order to tell the Spark kernel to go out and pull down the MLeap package from the Internet.  More on the Configuration parameter description here:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.run_job_flow

Information about that function's parameter is here: https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-configure-apps.html

In the AWS console, you can define what you need (see below) when configuring a cluster with support for MLeap v0.15.0:
```
{"classification":"spark-defaults","properties":{"spark.jars.packages":"ml.combust.mleap:mleap-spark_2.11:0.15.0"}}
```

I don't have a specific example that uses boto3's run_job_flow function, but you can extrapolate that Spark EMR configuration to use in the python code.

**Comment by juhoautio** [comment]
It’s mentioned here:

https://github.com/combust/mleap/blob/master/README.md#spark-packages

PySpark section should mention that this is needed.

**Comment by ancasarb** [comment]
@cappaberra @juhoautio Thank you, would it be possible to raise a PR to update the documentation as well? Thanks again!

**Comment by juhoautio** [comment]
@cappaberra would you like to do it? I can also do it if needed.

**Comment by guzzijones** [comment]
I tried to serialize a pipeline using v5.28 emr.  Mleap ended up crashing.  I am not able to install mleap on the emr version that uses 2.1 spark. Pandas fails to install.
Looks like i will have to just write the classifier to disk and zip up the resulting directory for now.

**Comment by juhoautio** [comment]
@guzzijones emr 5.28 installs spark 2.4.4. How does spark 2.1 come into the picture?

**Comment by guzzijones** [comment]
2.11 is the version mleap supports i believe...?

**Comment by juhoautio** [comment]
@guzzijones MLeap 0.11.0 should work with Spark 2.1. Maybe you saw 2.11 in some place that talks about scala version?

However, I would expect you to be using the latest version of MLeap (0.15.0), and if you're already on emr 5.28 then that gives you Spark 2.4.4 which should work fine.

If you have some reason of your own to using Spark 2.1, then have you tried MLeap 0.11.0? 

More versions (MLeap <-> Spark) are documented at https://github.com/combust/mleap#mleapspark-version. Have you seen this?

**Comment by guzzijones** [comment]
Mleap15 crashes when saving a pipeline using aws emr v5.28. I thought the
2.11 on the jar file was for the spark compatible version. I was wrong .

Do you use emr? Does it work for anyone here?

**Comment by guzzijones** [comment]
My custom tranformer was giving me fits too, unfortunately.

**Comment by juhoautio** [comment]
I have successfully used at least emr-5.20.0 with mleap==0.15.0 which has Spark 2.4.0. I don't see why it wouldn't work with 2.4.4. 

If you have a custom transformer you would need to add custom code at least for de/serializing it. Have you read https://mleap-docs.combust.ml/mleap-runtime/custom-transformer.html?

I understood you initially didn't add spark maven modules in spark session, and the error reported in this issue was because of that. What error do you get after fixing that? Sharing your code might help, too.

**Comment by guzzijones** [comment]
Ah, I think it was because I was using a zepplin notebook and the `import pyspark` could not be before the `spark` session setup since it is already done.
Do you have a zepplin notebook examle?

**Comment by guzzijones** [comment]
I will try this
https://github.com/combust/mleap-demo/blob/master/notebooks/PySpark%20-%20AirBnb.ipynb

**Comment by juhoautio** [comment]
Sure, if Zeppelin manages the spark session creation, then you should configure the additional maven modules (mleap) somewhere in zeppelin config.

**Comment by guzzijones** [comment]
we can close this.
